services:
  filefuse_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - B2_ACCESS_KEY_ID=xxxxxxxxxxxxxxxxxxxxxxxxxxx
      - B2_SECRET_ACCESS_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxx
      - B2_REGION=xxxxx
      - B2_BUCKET=xxxxxxxx
      - B2_ENDPOINT=xxxxxxxxxxxxxxxxxxxxxxxxxxx
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_USERNAME=xxxxxxxx
      - DB_PASSWORD=xxxxx
      - DB_NAME=xxxxxxxx
      - JWT_ACCESS_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxx
      - JWT_REFRESH_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxx
      - MAX_FILE_SIZE_LIMIT=100 * 1024 * 1024
    depends_on:
      - mysql_db
    volumes:
      - ./src:/app/src
  mysql_db:
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxxxx
      - MYSQL_DATABASE=xxxxxxxxxxxxxxxxxxxxxxxxxxx
      - MYSQL_USER=xxxxxxxxxxxxxxxxxxxxxxxxxxx
      - MYSQL_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxxxx
      - MYSQL_TCP_PORT=3307
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.nginx
      context: ./nginx
    ports:
      - '80:80'
    depends_on:
      - filefuse_api
